//! Do NOT edit this code.
//! It was automatically generated by Pavex.
//! All manual edits will be lost next time the code is generated.
extern crate alloc;
struct ServerState {
    router: pavex_matchit::Router<u32>,
    application_state: ApplicationState,
}
pub struct ApplicationState {
    s0: demo::repository::book::BookMemoryRepository,
}
pub async fn build_application_state() -> crate::ApplicationState {
    let v0 = demo::repository::book::BookMemoryRepository::new();
    crate::ApplicationState { s0: v0 }
}
pub fn run(
    server_builder: pavex::server::Server,
    application_state: ApplicationState,
) -> pavex::server::ServerHandle {
    let server_state = std::sync::Arc::new(ServerState {
        router: build_router(),
        application_state,
    });
    server_builder.serve(route_request, server_state)
}
fn build_router() -> pavex_matchit::Router<u32> {
    let mut router = pavex_matchit::Router::new();
    router.insert("/api/books", 0u32).unwrap();
    router.insert("/api/books/:id", 1u32).unwrap();
    router.insert("/api/greet/:name", 2u32).unwrap();
    router.insert("/api/ping", 3u32).unwrap();
    router
}
async fn route_request(
    request: http::Request<hyper::body::Incoming>,
    server_state: std::sync::Arc<ServerState>,
) -> pavex::response::Response {
    let (request_head, request_body) = request.into_parts();
    #[allow(unused)]
    let request_body = pavex::request::body::RawIncomingBody::from(request_body);
    let request_head: pavex::request::RequestHead = request_head.into();
    let matched_route = match server_state.router.at(&request_head.target.path()) {
        Ok(m) => m,
        Err(_) => {
            let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter(
                    vec![],
                )
                .into();
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "*",
            );
            return route_4::middleware_0(
                    &allowed_methods,
                    matched_route_template,
                    &request_head,
                )
                .await;
        }
    };
    let route_id = matched_route.value;
    #[allow(unused)]
    let url_params: pavex::request::path::RawPathParams<'_, '_> = matched_route
        .params
        .into();
    match route_id {
        0u32 => {
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "/api/books",
            );
            match &request_head.method {
                &pavex::http::Method::POST => {
                    route_2::middleware_0(
                            matched_route_template,
                            server_state.application_state.s0.clone(),
                            request_body,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::POST,
                        ])
                        .into();
                    route_4::middleware_0(
                            &allowed_methods,
                            matched_route_template,
                            &request_head,
                        )
                        .await
                }
            }
        }
        1u32 => {
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "/api/books/:id",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_3::middleware_0(
                            matched_route_template,
                            server_state.application_state.s0.clone(),
                            url_params,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_4::middleware_0(
                            &allowed_methods,
                            matched_route_template,
                            &request_head,
                        )
                        .await
                }
            }
        }
        2u32 => {
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "/api/greet/:name",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_0::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_4::middleware_0(
                            &allowed_methods,
                            matched_route_template,
                            &request_head,
                        )
                        .await
                }
            }
        }
        3u32 => {
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "/api/ping",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_1::middleware_0(matched_route_template, &request_head).await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_4::middleware_0(
                            &allowed_methods,
                            matched_route_template,
                            &request_head,
                        )
                        .await
                }
            }
        }
        i => unreachable!("Unknown route id: {}", i),
    }
}
pub mod route_0 {
    pub async fn middleware_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: pavex::request::path::RawPathParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = demo::telemetry::RootSpan::new(v2, v0);
        let v4 = <demo::telemetry::RootSpan as core::clone::Clone>::clone(&v3);
        let v5 = crate::route_0::Next0 {
            s_0: v1,
            s_1: v3,
            s_2: v2,
            next: handler,
        };
        let v6 = pavex::middleware::Next::new(v5);
        demo::telemetry::logger(v6, v4).await
    }
    pub async fn handler(
        v0: pavex::request::path::RawPathParams<'_, '_>,
        v1: demo::telemetry::RootSpan,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = demo::user_agent::UserAgent::extract(v2);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = demo::user_agent::invalid_user_agent(&v4);
                    let v6 = pavex::Error::new(v4);
                    demo::telemetry::log_error(&v6, v1).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        let v5 = pavex::request::path::PathParams::extract(v0);
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = pavex::request::path::errors::ExtractPathParamsError::into_response(
                        &v6,
                    );
                    let v8 = pavex::Error::new(v6);
                    demo::telemetry::log_error(&v8, v1).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v7,
                    )
                };
            }
        };
        let v7 = demo::routes::greet::greet(v6, v4);
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v7)
    }
    pub struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::path::RawPathParams<'a, 'b>,
        s_1: demo::telemetry::RootSpan,
        s_2: &'c pavex::request::RequestHead,
        next: fn(
            pavex::request::path::RawPathParams<'a, 'b>,
            demo::telemetry::RootSpan,
            &'c pavex::request::RequestHead,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2)
        }
    }
}
pub mod route_1 {
    pub async fn middleware_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v2 = demo::telemetry::RootSpan::new(v1, v0);
        let v3 = crate::route_1::Next0 {
            next: handler,
        };
        let v4 = pavex::middleware::Next::new(v3);
        demo::telemetry::logger(v4, v2).await
    }
    pub async fn handler() -> pavex::response::Response {
        let v0 = demo::routes::status::ping();
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v0)
    }
    pub struct Next0<T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        next: fn() -> T,
    }
    impl<T> std::future::IntoFuture for Next0<T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)()
        }
    }
}
pub mod route_2 {
    pub async fn middleware_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: demo::repository::book::BookMemoryRepository,
        v2: pavex::request::body::RawIncomingBody,
        v3: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v4 = demo::telemetry::RootSpan::new(v3, v0);
        let v5 = <demo::telemetry::RootSpan as core::clone::Clone>::clone(&v4);
        let v6 = crate::route_2::Next0 {
            s_0: v1,
            s_1: v2,
            s_2: v4,
            s_3: v3,
            next: handler,
        };
        let v7 = pavex::middleware::Next::new(v6);
        demo::telemetry::logger(v7, v5).await
    }
    pub async fn handler(
        v0: demo::repository::book::BookMemoryRepository,
        v1: pavex::request::body::RawIncomingBody,
        v2: demo::telemetry::RootSpan,
        v3: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v4 = <pavex::request::body::BodySizeLimit as std::default::Default>::default();
        let v5 = pavex::request::body::BufferedBody::extract(v3, v1, v4).await;
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v6,
                    );
                    let v8 = pavex::Error::new(v6);
                    demo::telemetry::log_error(&v8, v2).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v7,
                    )
                };
            }
        };
        let v7 = pavex::request::body::JsonBody::extract(v3, &v6);
        let v8 = match v7 {
            Ok(ok) => ok,
            Err(v8) => {
                return {
                    let v9 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v8,
                    );
                    let v10 = pavex::Error::new(v8);
                    demo::telemetry::log_error(&v10, v2).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v9,
                    )
                };
            }
        };
        let v9 = demo::routes::books::save(v8, v0);
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v9)
    }
    pub struct Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: demo::repository::book::BookMemoryRepository,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: demo::telemetry::RootSpan,
        s_3: &'a pavex::request::RequestHead,
        next: fn(
            demo::repository::book::BookMemoryRepository,
            pavex::request::body::RawIncomingBody,
            demo::telemetry::RootSpan,
            &'a pavex::request::RequestHead,
        ) -> T,
    }
    impl<'a, T> std::future::IntoFuture for Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3)
        }
    }
}
pub mod route_3 {
    pub async fn middleware_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: demo::repository::book::BookMemoryRepository,
        v2: pavex::request::path::RawPathParams<'_, '_>,
        v3: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v4 = demo::telemetry::RootSpan::new(v3, v0);
        let v5 = <demo::telemetry::RootSpan as core::clone::Clone>::clone(&v4);
        let v6 = crate::route_3::Next0 {
            s_0: v1,
            s_1: v2,
            s_2: v4,
            next: handler,
        };
        let v7 = pavex::middleware::Next::new(v6);
        demo::telemetry::logger(v7, v5).await
    }
    pub async fn handler(
        v0: demo::repository::book::BookMemoryRepository,
        v1: pavex::request::path::RawPathParams<'_, '_>,
        v2: demo::telemetry::RootSpan,
    ) -> pavex::response::Response {
        let v3 = pavex::request::path::PathParams::extract(v1);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::request::path::errors::ExtractPathParamsError::into_response(
                        &v4,
                    );
                    let v6 = pavex::Error::new(v4);
                    demo::telemetry::log_error(&v6, v2).await;
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        let v5 = demo::routes::books::get_by_id(v4, v0);
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v5)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: demo::repository::book::BookMemoryRepository,
        s_1: pavex::request::path::RawPathParams<'a, 'b>,
        s_2: demo::telemetry::RootSpan,
        next: fn(
            demo::repository::book::BookMemoryRepository,
            pavex::request::path::RawPathParams<'a, 'b>,
            demo::telemetry::RootSpan,
        ) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2)
        }
    }
}
pub mod route_4 {
    pub async fn middleware_0(
        v0: &pavex::router::AllowedMethods,
        v1: pavex::request::path::MatchedPathPattern,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = demo::telemetry::RootSpan::new(v2, v1);
        let v4 = crate::route_4::Next0 {
            s_0: v0,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        demo::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: &pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let v1 = pavex::router::default_fallback(v0).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v1)
    }
    pub struct Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex::router::AllowedMethods,
        next: fn(&'a pavex::router::AllowedMethods) -> T,
    }
    impl<'a, T> std::future::IntoFuture for Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
